version: '2'
services:
  listener:
    build: .
    depends_on:
      - redis
      - mysql
    ports:
     - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=compose
  redis:
    image: "redis:alpine"
  mysql:
    image: "mysql/mysql-server:5.7"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_ROOT_PASSWORD=""
      - MYSQL_DATABASE="listener"
      - MYSQL_ROOT_HOST=0.0.0.0