spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:mysql://localhost:3306/listener?useTimezone=true&serverTimezone=UTC
    username: root
    password:
  properties:
    hibernate:
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect


logging.level.org.hibernate.SQL: debug

---

spring:
  profiles: default

redis:
  hostname: localhost

io:
  block16:
    nodeLocation: https://mainnet.infura.io/mMVAl9ZCBbtZ4sc0fBbO


---

spring:
  profiles: compose

redis:
  hostname: redis

io:
  block16:
    nodeLocation: https://mainnet.infura.io/mMVAl9ZCBbtZ4sc0fBbO

---

spring:
  profiles: prod

io:
  block16:
    nodeLocation: https://mainnet.infura.io/mMVAl9ZCBbtZ4sc0fBbO