
io:
  block16:
    concurrency: 20

---

spring:
  profiles: default

io:
  block16:
#    nodeLocation: https://mainnet.infura.io/mMKKl8ZdBbtZ4sc0fBBO
    nodeLocation: https://mainnet.infura.io/rN9AdvkVRuc7HkkUJbnl

server:
  port: 8082


---

spring:
  profiles: compose

io:
  block16:
    nodeLocation: https://mainnet.infura.io/rN9AdvkVRuc7HkkUJbnl

server:
  port: 8080

---

spring:
  profiles: prod

io:
  block16:
    nodeLocation: https://mainnet.infura.io/rN9AdvkVRuc7HkkUJbnl

server:
  port: 8080