
io:
  block16:
    concurrency: 10

---

spring:
  profiles: default

io:
  block16:
#    nodeLocation: https://mainnet.infura.io/mMKKl8ZdBbtZ4sc0fBBO
    nodeLocation: http://localhost:8546

server:
  port: 8082


---

spring:
  profiles: compose

io:
  block16:
    nodeLocation: https://mainnet.infura.io/mMVAl9ZCBbtZ4sc0fBbO

server:
  port: 8080

---

spring:
  profiles: prod

io:
  block16:
    nodeLocation: http://localhost:8545

server:
  port: 8080