spring:
  jpa:
    hibernate:
      ddl-auto: none
  properties:
    hibernate:
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect

logging.level.org.hibernate.SQL: debug

flyway:
  locations: classpath:flyway

---

spring:
  profiles: default
  datasource:
    url: jdbc:mysql://localhost:3306/listener?useTimezone=true&serverTimezone=UTC&useSSL=false
    username: root
    password:

redis:
  hostname: localhost

io:
  block16:
    # nodeLocation: http://localhost:8546
    nodeLocation: https://mainnet.infura.io/mMVAl9ZCBbtZ4sc0fBbO


---

spring:
  profiles: compose
  datasource:
    url: jdbc:mysql://mysql:3306/listener?useTimezone=true&serverTimezone=UTC&useSSL=false
    username: root
    password:

redis:
  hostname: redis

io:
  block16:
    nodeLocation: https://mainnet.infura.io/mMVAl9ZCBbtZ4sc0fBbO

---

spring:
  profiles: prod
  datasource:
    url: jdbc:mysql://mysql.internal.block16:3306/listener?useTimezone=true&serverTimezone=UTC&useSSL=false
    username: andrew
    max-active: 128

redis:
  hostname: redis.internal.block16

io:
  block16:
    nodeLocation: https://mainnet.infura.io/mMVAl9ZCBbtZ4sc0fBbO