spring:
  jpa:
    hibernate:
      ddl-auto: none
  properties:
    hibernate:
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect

logging.level.org.hibernate.SQL: debug

server:
  port: 8082

io:
  block16:
    concurrency: 50

---

spring:
  profiles: default

redis:
  hostname: localhost

io:
  block16:
#    nodeLocation: https://mainnet.infura.io/mMKKl8ZdBbtZ4sc0fBBO
    nodeLocation: http://localhost:8546


---

spring:
  profiles: compose
redis:
  hostname: redis

io:
  block16:
    nodeLocation: https://mainnet.infura.io/mMVAl9ZCBbtZ4sc0fBbO

---

spring:
  profiles: prod

redis:
  hostname: redis.internal.block16

io:
  block16:
    nodeLocation: https://mainnet.infura.io/mMVAl9ZCBbtZ4sc0fBbO